### ISSUE TITLE
error with is_user_authorized()

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/roreviewapi#53]
![image](https://github.com/ropensci-review-tools/roreviewapi/assets/8360597/ea803910-d358-40e0-8eff-b115929b9016)

**Comment by mpadge** [comment]
Sorry, that's because of this line:
https://github.com/ropensci-review-tools/roreviewapi/blob/17aa14b7ffe7ba297d1917dadd250117127703c4/R/utils.R#L24
as documented in README:
https://github.com/ropensci-review-tools/roreviewapi/blob/17aa14b7ffe7ba297d1917dadd250117127703c4/README.md?plain=1#L31-L33
So this pkg expects that to exist. gitcreds isn't used, because it's much easier to work directly with envvars on the server itself (and also that's how the actual gh cli works too). But if you had time, you could fix it by submitting a PR which inserts lines after that with `if (is.null(gh_tok)) ...` try gitcreds to get it. That'd be great, thanks!
